export const TOP_DESTINATIONS = [
  {
    id: 'dubai',
    name: 'Dubai',
    country: 'UAE',
    currency: 'AED',
    emoji: '☀️',
    weatherType: 'hot-dry',
    avgTemp: { min: 25, max: 45 },
    kidsHighlights: ['Dubai Mall Aquarium', 'Legoland', 'IMG Worlds', 'Beach parks'],
    packingNotes: 'Very hot - pack light cotton, sun protection essential',
  },
  {
    id: 'singapore',
    name: 'Singapore',
    country: 'Singapore',
    currency: 'SGD',
    emoji: '🏙️',
    weatherType: 'hot-humid',
    avgTemp: { min: 25, max: 32 },
    kidsHighlights: ['Universal Studios', 'Singapore Zoo', 'SEA Aquarium', 'Gardens by the Bay'],
    packingNotes: 'Hot and humid - pack light breathable clothes, rain jacket',
  },
  {
    id: 'thailand',
    name: 'Thailand',
    country: 'Thailand',
    currency: 'THB',
    emoji: '🌴',
    weatherType: 'hot-humid',
    avgTemp: { min: 26, max: 35 },
    kidsHighlights: ['Beaches', 'Elephant sanctuaries', 'Water parks', 'Night markets'],
    packingNotes: 'Hot and humid - mosquito repellent essential, modest clothes for temples',
  },
  {
    id: 'bali',
    name: 'Bali',
    country: 'Indonesia',
    currency: 'IDR',
    emoji: '🏝️',
    weatherType: 'tropical',
    avgTemp: { min: 24, max: 30 },
    kidsHighlights: ['Waterbom', 'Monkey Forest', 'Beach clubs', 'Rice terraces'],
    packingNotes: 'Tropical - reef-safe sunscreen, bug spray, rash guards for beach',
  },
  {
    id: 'malaysia',
    name: 'Malaysia',
    country: 'Malaysia',
    currency: 'MYR',
    emoji: '🦜',
    weatherType: 'hot-humid',
    avgTemp: { min: 25, max: 33 },
    kidsHighlights: ['Petronas Towers', 'Legoland', 'Langkawi beaches', 'Genting'],
    packingNotes: 'Hot and humid - light clothes, rain gear, mosquito patches',
  },
  {
    id: 'maldives',
    name: 'Maldives',
    country: 'Maldives',
    currency: 'MVR',
    emoji: '🐚',
    weatherType: 'tropical',
    avgTemp: { min: 26, max: 31 },
    kidsHighlights: ['Snorkeling', 'Resort kids clubs', 'Water villas', 'Dolphin watching'],
    packingNotes: 'Tropical island - water shoes, reef-safe sunscreen, snorkel gear',
  },
  {
    id: 'sri-lanka',
    name: 'Sri Lanka',
    country: 'Sri Lanka',
    currency: 'LKR',
    emoji: '🐘',
    weatherType: 'tropical',
    avgTemp: { min: 24, max: 32 },
    kidsHighlights: ['Elephant orphanage', 'Train rides', 'Beaches', 'Wildlife safaris'],
    packingNotes: 'Tropical - light clothes, bug spray, comfortable shoes for temples',
  },
  {
    id: 'vietnam',
    name: 'Vietnam',
    country: 'Vietnam',
    currency: 'VND',
    emoji: '🛶',
    weatherType: 'varies',
    avgTemp: { min: 22, max: 33 },
    kidsHighlights: ['Ha Long Bay', 'Beaches', 'Water puppets', 'Cu Chi tunnels'],
    packingNotes: 'Varies by region - check specific city weather, mosquito protection',
  },
  {
    id: 'mauritius',
    name: 'Mauritius',
    country: 'Mauritius',
    currency: 'MUR',
    emoji: '🌺',
    weatherType: 'tropical',
    avgTemp: { min: 20, max: 30 },
    kidsHighlights: ['Beaches', 'Casela Nature Park', 'Underwater waterfall', 'Ile aux Cerfs'],
    packingNotes: 'Tropical - beach gear, sunscreen, light layers for evenings',
  },
  {
    id: 'abu-dhabi',
    name: 'Abu Dhabi',
    country: 'UAE',
    currency: 'AED',
    emoji: '🎢',
    weatherType: 'hot-dry',
    avgTemp: { min: 25, max: 42 },
    kidsHighlights: ['Ferrari World', 'Yas Waterworld', 'Louvre Abu Dhabi', 'Emirates Park Zoo'],
    packingNotes: 'Very hot - same as Dubai, sun protection critical',
  },
  {
    id: 'hong-kong',
    name: 'Hong Kong',
    country: 'Hong Kong',
    currency: 'HKD',
    emoji: '🎡',
    weatherType: 'subtropical',
    avgTemp: { min: 16, max: 31 },
    kidsHighlights: ['Hong Kong Disneyland', 'Ocean Park', 'Peak Tram', 'Star Ferry'],
    packingNotes: 'Check season - summers humid, winters mild, always pack layers',
  },
  {
    id: 'japan',
    name: 'Japan',
    country: 'Japan',
    currency: 'JPY',
    emoji: '🗾',
    weatherType: 'seasonal',
    avgTemp: { min: 2, max: 32 },
    kidsHighlights: ['Tokyo Disneyland', 'Universal Studios', 'Robot Restaurant', 'Deer park Nara'],
    packingNotes: 'Highly seasonal - check dates carefully, comfortable walking shoes essential',
  },
  {
    id: 'australia',
    name: 'Australia',
    country: 'Australia',
    currency: 'AUD',
    emoji: '🦘',
    weatherType: 'varies',
    avgTemp: { min: 10, max: 30 },
    kidsHighlights: ['Wildlife parks', 'Beaches', 'Great Barrier Reef', 'Theme parks'],
    packingNotes: 'Opposite seasons - summer Dec-Feb, strong sun protection needed',
  },
  {
    id: 'uk',
    name: 'London',
    country: 'UK',
    currency: 'GBP',
    emoji: '🎡',
    weatherType: 'cold-rainy',
    avgTemp: { min: 5, max: 22 },
    kidsHighlights: ['Harry Potter Studios', 'London Eye', 'Natural History Museum', 'Legoland'],
    packingNotes: 'Unpredictable weather - layers essential, waterproof jacket, umbrella',
  },
  {
    id: 'europe',
    name: 'Europe',
    country: 'Multiple',
    currency: 'EUR',
    emoji: '🏰',
    weatherType: 'seasonal',
    avgTemp: { min: 0, max: 28 },
    kidsHighlights: ['Disneyland Paris', 'Swiss Alps', 'Eiffel Tower', 'Castles'],
    packingNotes: 'Highly seasonal - check specific countries, comfortable walking shoes',
  },
];

export function getDestinationByName(name: string) {
  const searchName = name.toLowerCase();
  return TOP_DESTINATIONS.find(d =>
    d.name.toLowerCase().includes(searchName) ||
    d.country.toLowerCase().includes(searchName) ||
    d.id.includes(searchName)
  );
}

export function getCurrencyForCountry(country: string): string {
  const currencyMap: Record<string, string> = {
    'UAE': 'AED',
    'United Arab Emirates': 'AED',
    'Singapore': 'SGD',
    'Thailand': 'THB',
    'Indonesia': 'IDR',
    'Malaysia': 'MYR',
    'Maldives': 'MVR',
    'Sri Lanka': 'LKR',
    'Vietnam': 'VND',
    'Mauritius': 'MUR',
    'Hong Kong': 'HKD',
    'Japan': 'JPY',
    'Australia': 'AUD',
    'UK': 'GBP',
    'United Kingdom': 'GBP',
    'USA': 'USD',
    'United States': 'USD',
    'France': 'EUR',
    'Germany': 'EUR',
    'Italy': 'EUR',
    'Spain': 'EUR',
    'Multiple': 'EUR',
    'Switzerland': 'CHF',
  };
  return currencyMap[country] || 'USD';
}
